1. Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

In [8]:
import numpy as np

a = np.linspace(1, 10, num=10, dtype=int)
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


2.Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.

In [ ]:
import numpy as np

m = np.zeros((3, 3), dtype=int)
print(m)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


3.Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.

In [7]:
import numpy as np

b = np.random.randint(1,11, size=(5,5))
print(b)

[[ 8  1  6  2  9]
 [ 9  2  1 10  9]
 [ 1  4  1  9  9]
 [10 10  2  9 10]
 [ 8  1  4  6  8]]


4. Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

In [ ]:
import numpy as np

b = np.random.random((4, 4))
print(b)

[[0.61579246 0.81529844 0.76335997 0.43550018]
 [0.17207573 0.36998987 0.28527527 0.28483146]
 [0.24369459 0.47325003 0.84887249 0.53660042]
 [0.61738597 0.59850981 0.50762101 0.204729  ]]


5.
Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

In [15]:
import numpy as np

a = np.random.randint(1,11, size=(5,1))
b = np.random.randint(1,11, size=(5,1))
print("A= ", a)
print("B= ", b)
print("A+B= ",a+b)
print("A-B= ",a-b)
print("A*B= ",a*b)

A=  [[10]
 [ 1]
 [ 6]
 [ 8]
 [ 7]]
B=  [[10]
 [ 2]
 [ 5]
 [ 9]
 [ 9]]
A+B=  [[20]
 [ 3]
 [11]
 [17]
 [16]]
A-B=  [[ 0]
 [-1]
 [ 1]
 [-1]
 [-2]]
A*B=  [[100]
 [  2]
 [ 30]
 [ 72]
 [ 63]]


6.Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

In [1]:
import numpy as np
arr = np.array([1,3,5,6,8,9,1])
brr = np.array([5,3,-7,6,8,3,1])

c = np.dot(arr,brr)
print(c)

107


7.Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

In [2]:
import numpy as np
a = np.random.randint(1,11, size=(2,2))
b = np.random.randint(1,11, size=(2,3))
print(a)
print(b)
print(np.dot(a,b))

[[123  46 107]
 [ 67  31  45]]


8.Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

In [3]:
import numpy as np
a = np.random.randint(1,11, size=(3,3))
a_inv = np.linalg.inv(a)
print(a_inv)

[[-0.49659864  0.30612245  0.2244898 ]
 [ 0.40816327 -0.26530612 -0.06122449]
 [-0.19727891  0.24489796 -0.02040816]]


9.Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [5]:
import numpy as np

b = np.random.random((4, 4)).round(2)
print(b)
print(b.T)

[[0.26 1.   0.98 0.2 ]
 [0.04 0.05 0.82 0.93]
 [0.72 0.01 0.5  0.26]
 [0.6  0.38 0.97 0.19]]
[[0.26 0.04 0.72 0.6 ]
 [1.   0.05 0.01 0.38]
 [0.98 0.82 0.5  0.97]
 [0.2  0.93 0.26 0.19]]


10.Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.

In [7]:
import numpy as np
a = np.random.randint(1,11, size=(3,4))
b = np.random.randint(1,11, size=(4,1))
print(a)
print(b)
print(np.dot(a,b))

[[113]
 [100]
 [122]]


11.Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.

In [3]:
import numpy as np

a = np.random.random((2, 3)).round(2)
b = np.random.random((3, 1)).round(2)
print(a)
print(b)
print(np.dot(a,b))

[[0.73 0.9  0.03]
 [0.56 0.36 0.91]]
[[0.34]
 [0.05]
 [0.16]]
[[0.298]
 [0.354]]


12.Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

In [10]:
import numpy as np
a = np.random.randint(1,11, size=(2,2))
b = np.random.randint(1,11, size=(2,2))
print(a)
print(b)
print(a*b)

[[10  3]
 [ 4  4]]
[[9 6]
 [4 8]]
[[90 18]
 [16 32]]


13.Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.

In [11]:
import numpy as np
a = np.random.randint(1,11, size=(2,2))
b = np.random.randint(1,11, size=(2,2))
print(a)
print(b)
print(np.dot(a,b))

[[9 1]
 [3 2]]
[[8 6]
 [3 5]]
[[75 59]
 [30 28]]


14.Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.

In [12]:
import numpy as np
a = np.random.randint(1,101, size=(5,5))
print(a)
print(a.sum())

[[56  9 63 10  9]
 [55 27 59 13 57]
 [82 61 29 64 17]
 [96 34 66 45  6]
 [50 92 18  9 16]]
1043


15.Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

In [13]:
import numpy as np
a = np.random.randint(1,11, size=(4,4))
b = np.random.randint(1,11, size=(4,4))
print(a)
print(b)
print(a-b)

[[8 4 9 6]
 [6 6 8 7]
 [8 7 1 5]
 [8 7 7 4]]
[[1 7 7 1]
 [4 5 1 5]
 [7 9 3 8]
 [4 7 2 5]]
[[ 7 -3  2  5]
 [ 2  1  7  2]
 [ 1 -2 -2 -3]
 [ 4  0  5 -1]]


16.Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [2]:
import numpy as np
a = np.random.random((3, 3)).round(2)
b = np.array([[a[:1,:].sum()],[a[1:2,:].sum()],[a[2:,:].sum()]])
c = np.sum(a, axis=1).reshape((-1, 1))
print(a)
print(b)
print(c)

[[0.62 0.44 0.96]
 [0.3  0.93 0.01]
 [0.71 0.97 0.39]]
[[2.02]
 [1.24]
 [2.07]]
[[2.02]
 [1.24]
 [2.07]]


17.Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.

In [19]:
import numpy as np
a = np.array([[1,3,5,6],[1,5,7,9],[5,7,2,6],[14,7,9,6]])
b = np.square(a)
print(a)
print(b)


[[ 1  3  5  6]
 [ 1  5  7  9]
 [ 5  7  2  6]
 [14  7  9  6]]
[[  1   9  25  36]
 [  1  25  49  81]
 [ 25  49   4  36]
 [196  49  81  36]]


18.Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.

In [20]:
import numpy as np
a = np.random.randint(1,51, size=(4,1))
b = np.sqrt(a)
print(a)
print(b)

[[45]
 [13]
 [14]
 [41]]
[[6.70820393]
 [3.60555128]
 [3.74165739]
 [6.40312424]]
